server:
  image: postgrest/postgrest
  ports:
    - "3000:3000"
  links:
    - db:db
  environment:
    PGRST_DB_URI: postgres://app_user:password@db:5432/postgres
    PGRST_DB_SCHEMA: movies
    PGRST_DB_ANON_ROLE: app_user
    PGRST_SERVER_PROXY_URI: http://localhost:3000/
db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_DB: movies
    POSTGRES_USER: app_user
    POSTGRES_PASSWORD: password
